#!/bin/bash

set -ouex pipefail

echo "::group::Executing install_packages"
trap 'echo "::endgroup::"' EXIT

dnf5 -y install \
    twitter-twemoji-fonts \
    lato-fonts \
    fira-code-fonts \
    nerd-fonts \
    google-droid-sans-mono-fonts \
    python3-pip \
    duperemove \
    ddcutil \
    input-remapper \
    i2c-tools \
    lm_sensors \
    udica \
    python3-icoextract \
    webapp-manager \
    zsh \
    btop \
    libbluray \
    libbluray-utils \
    fdk-aac \
    ffmpeg-libs \
    ffmpegthumbnailer \
    ffmpeg \
    libcec \
    f3 \
    lzip \
    p7zip \
    rar \
    vulkan-tools \
    cdemu-daemon \
    cdemu-client \
    gcdemu \
    openrazer-meta \
    egl-utils \
    ncdu \
    btrfs-assistant \
    podman-compose \
    unetbootin \
    antimicrox \
    lsb_release \
    alsa-firmware \
    android-udev-rules \
    distrobox \
    flatpak-spawn \
    fuse \
    fzf \
    grub2-tools-extra \
    heif-pixbuf-loader \
    htop \
    iperf3 \
    lshw \
    net-tools \
    nvme-cli \
    nvtop \
    openrgb-udev-rules \
    pam-u2f \
    pam_yubico \
    pamu2fcfg \
    pipewire-libs-extra \
    pipewire-plugin-libcamera \
    powerstat \
    lxpolkit \
    smartmontools \
    squashfs-tools \
    symlinks \
    tcpdump \
    screen \
    traceroute \
    vim \
    wireguard-tools \
    wl-clipboard \
    yubikey-manager \
    yubico-piv-tool \
    adw-gtk3-theme \
    gvfs-nfs \
    gvfs-mtp \
    gvfs-smb \
    gvfs-gphoto2 \
    gvfs-fuse \
    gstreamer1-plugin-libav \
    gstreamer1-plugins-ugly \
    gstreamer1-plugins-bad \
    gstreamer1-plugins-good-extras \
    openssh-askpass \
    cyanrip \
    sway \
    swayidle \
    waybar \
    fuzzel \
    alacritty \
    pcsc-lite-devel \
    mediawriter \
    wev \
    SwayNotificationCenter \
    firewall-config \
    gdm \
    alsa-utils \
    bc \
    hdparm \
    nautilus \
    nautilus-extensions \
    pipewire-utils \
    rsync \
    tuned \
    wget \
    flatpak \
    gnome-software \
    gnome-disk-utility \
    gamemode \
    git \
    cups \
    glibc-all-langpacks \
    google-noto-sans-jp-fonts \
    rom-properties-gtk3 \
    pipewire-pulseaudio \
    authselect \
    zip \
    netcat \
    wlr-randr
