name: Build DrelbsOS container image
on:
  schedule:
    - cron: '05 10 * * 3'  # 10:05am UTC wed
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  merge_group:
  workflow_dispatch:
    inputs:
      # Run with this periodically to analyze the image again
      # As package drift will make the plan eventually non-ideal
      # (existing users will have to redownload most of the image)
      fresh-rechunk:
        description: 'Clear rechunk history'
        type: boolean
        default: false
env:
  IMAGE_DESC: "DrelbsOS"
  IMAGE_KEYWORDS: "bootc,fedora"
  IMAGE_LOGO_URL: ""
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  FEDORA_MAJOR_VERSION: "44"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-24.04
    continue-on-error: false
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Define env.SHA_HEAD_SHORT
        id: shortsha
        run: |
          echo "SHA_HEAD_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Get current date
        id: date
        run: |
          # This generates a timestamp like what is defined on the ArtifactHub documentation
          # E.G: 2022-02-08T15:38:15Z'
          # https://artifacthub.io/docs/topics/repositories/container-images/
          # https://linux.die.net/man/1/date
          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          echo "date=$TIMESTAMP" >> $GITHUB_OUTPUT
          # However, OCI *tags* do not like this format,so munge for that usage.
          echo "date_tag=${TIMESTAMP//:/-}" >> $GITHUB_OUTPUT

      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@90e01b21170618765a73370fcc3abbd1684a7793 # v5
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
          remove-large-packages: true
          remove-cached-tools: true
          remove-swapfile: true

      # Generate a primary version key
      - name: Generate Version
        id: generate-version
        shell: bash
        run: |
          # Generate the primary version key that will be stored on os-release,
          # shown on the bootloader, and used for the image tag.
          VERSION="${FEDORA_MAJOR_VERSION}.${{ steps.date.outputs.date_tag }}"

          echo "tag=${VERSION}" >> $GITHUB_OUTPUT

          echo "Generated the following:"
          cat $GITHUB_OUTPUT

      # Build image using buildah and save it to raw-img
      - name: Build Image
        id: build_image
        run: |
          sudo buildah build \
            --build-arg IMAGE_NAME=${{ env.IMAGE_NAME }} \
            --build-arg FEDORA_MAJOR_VERSION=${{ env.FEDORA_MAJOR_VERSION }} \
            --build-arg IMAGE_BRANCH=${{ github.ref_name }} \
            --build-arg IMAGE_BUILDID=${{ steps.generate-version.outputs.tag }} \
            --tag raw-img .

      # Generate the previous image reference used by the Rechunker
      - name: Generate previous reference
        id: generate-prev-ref
        shell: bash
        run: |
          if [ "${{ github.event.inputs.fresh-rechunk }}" == "true" ]; then
            IMAGEREF=""
          else
            IMAGEREF="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:main"
          fi

          echo "ref=${IMAGEREF}" >> $GITHUB_OUTPUT

          echo "Generated the following:"
          cat $GITHUB_OUTPUT

      # Reprocess raw-img using rechunker which will delete it
      - name: Run Rechunker
        id: rechunk
        uses: hhd-dev/rechunk@v1.2.4
        with:
          rechunk: 'ghcr.io/hhd-dev/rechunk:v1.2.4'
          ref: 'raw-img'
          prev-ref: '${{ steps.generate-prev-ref.outputs.ref }}'
          version: '${{ steps.generate-version.outputs.tag }}'
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/${{ github.sha }}/README.md
            org.opencontainers.image.created=<timestamp>
            org.opencontainers.image.description=${{ env.IMAGE_DESC }}
            org.opencontainers.image.documentation=https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/${{ github.sha }}/README.md
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/blob/${{ github.sha }}/Containerfile
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}/tree/${{ github.sha }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ steps.generate-version.outputs.tag }}
            org.universal-blue.pkg.kernel=<relver:kernel>
            org.fedoraproject.coreos.ostree.version=${{ steps.generate-version.outputs.tag }}
            io.artifacthub.package.deprecated=false
            io.artifacthub.package.keywords=${{ env.IMAGE_KEYWORDS }}
            io.artifacthub.package.license=Apache-2.0
            io.artifacthub.package.logo-url=${{ env.IMAGE_LOGO_URL }}
            io.artifacthub.package.prerelease=false
            containers.bootc=1


      # Generate tags after rechunker runs and checks the primary tag is not duplicated
      # If it is, rechunk will suffix it by .1, .2, etc and put it in steps.rechunk.outputs.version
      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          BUILD_TAGS=( "${{ steps.rechunk.outputs.version }}" )

          # Add other variants
          BUILD_TAGS+=("${FEDORA_MAJOR_VERSION}")
          BUILD_TAGS+=("${{ github.ref_name }}-${{ steps.rechunk.outputs.version }}")

          # Per fedora version
          BUILD_TAGS+=("${FEDORA_MAJOR_VERSION}-${{ github.ref_name }}")

          BUILD_TAGS+=("latest" "${{ github.ref_name }}")

          echo "Generated the following build tags: "
          for TAG in "${BUILD_TAGS[@]}"; do
              echo "${TAG}"
          done
          echo "alias_tags=${BUILD_TAGS[*]}" >> $GITHUB_OUTPUT

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: Wandalen/wretry.action@e68c23e6309f2871ca8ae4763e7629b9c258e1ea # v3.8.0
        id: push
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        with:
          attempt_limit: 3
          attempt_delay: 15000
          command: |
            echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin
            for tag in ${{ steps.generate-tags.outputs.alias_tags }}; do
              sudo skopeo copy ${{ steps.rechunk.outputs.ref }} docker://${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:$tag
            done

      - name: Get Image Digest
        id: digest
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        run: |
          # Get digest for signing
          DIGEST=$(sudo skopeo inspect --format '{{.Digest}}' ${{ steps.rechunk.outputs.ref }})
          echo "Digest is: $DIGEST"
          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT

      - name: Install Cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        with:
          cosign-release: 'v2.6.1'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v3
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign container image
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        run: |
          IMAGE_FULL="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"
          for tag in ${{ steps.generate-tags.outputs.alias_tags }}; do
            cosign sign -y --key env://COSIGN_PRIVATE_KEY $IMAGE_FULL:$tag
          done
        env:
          TAGS: ${{ steps.digest.outputs.digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}

  generate_release:
    name: Generate Release
    needs: [push-ghcr]
    if: github.event_name != 'pull_request'
    secrets: inherit
    permissions:
      contents: write  # Required for creating releases
    uses: ./.github/workflows/generate-release.yml
